export const ROLES_KEY = 'roles';
export const IS_PUBLIC_KEY = 'isPublic';

export const SYSTEM_USER_ID = '00000000-0000-0000-0000-000000000000';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONFLICT: 'CONFLICT',
  RESOURCE_EXISTS: 'RESOURCE_EXISTS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
};
