export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  REMINDER = 'REMINDER',
  PAYMENT = 'PAYMENT',
  CANCELLATION = 'CANCELLATION',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  SYSTEM = 'SYSTEM',
}
